parameters:
  BuildPlatform: ''

steps:
- task: CMake@1
  displayName: 'Configure'
  inputs:
    cmakeArgs: '.. -G"Visual Studio 15 2017 ${{ parameters.BuildPlatform }}"'

- bash: |
    ls -lh build

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: build/openttd.sln
    maximumCpuCount: true
